# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LBComputeServerCom.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18LBComputeServerCom.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n\rRawMeteoData2\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"[\n\x11RawPollutionData2\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03\x63o2\x18\x02 \x01(\x02\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x9e\x01\n\x14\x43omputeServerService\x12>\n\x12process_meteo_data\x12\x0e.RawMeteoData2\x1a\x16.google.protobuf.Empty\"\x00\x12\x46\n\x16process_pollution_data\x12\x12.RawPollutionData2\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LBComputeServerCom_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAWMETEODATA2._serialized_start=90
  _RAWMETEODATA2._serialized_end=203
  _RAWPOLLUTIONDATA2._serialized_start=205
  _RAWPOLLUTIONDATA2._serialized_end=296
  _COMPUTESERVERSERVICE._serialized_start=299
  _COMPUTESERVERSERVICE._serialized_end=457
# @@protoc_insertion_point(module_scope)
