# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import proxyTerminalCom_pb2 as proxyTerminalCom__pb2


class TerminalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_results = channel.unary_unary(
                '/TerminalService/send_results',
                request_serializer=proxyTerminalCom__pb2.Coefficients.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class TerminalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_results(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_results': grpc.unary_unary_rpc_method_handler(
                    servicer.send_results,
                    request_deserializer=proxyTerminalCom__pb2.Coefficients.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TerminalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TerminalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_results(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TerminalService/send_results',
            proxyTerminalCom__pb2.Coefficients.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
